# **Installing Pre-requisites for our Analysis**

In [1]:
!pip install pandas
!pip install scikit-learn

Requirement already satisfied: pandas in d:\miniconda\miniconda\envs\ml\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: scikit-learn in d:\miniconda\miniconda\envs\ml\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from scikit-learn) (2.0.0)
Requirement already satisfied: scipy>=1.6.0 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\miniconda\miniconda\envs\ml\lib\site-packages (from scikit-learn) (3.5.0)

In [2]:
import pandas as pd

Storing the dataset in a variable

In [3]:
dataset_for_training = r"C:/Users/edwin victor/git repositories/dsp-edwinvictor-justin/data/train.csv"

# **Reading the csv file using read_csv function**

In [4]:
Training_dataset = pd.read_csv(dataset_for_training)
Training_dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# **Analyzing the dataset to get overview using some commonly used pandas functions**

In [5]:
Training_dataset.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [6]:
Training_dataset.tail(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [7]:
Training_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [8]:
Training_dataset.describe() #to get a statistical overview about this dataset

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [9]:
Training_dataset.columns #to get names of the columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [10]:
Training_dataset.shape  #totally there are 1460 rows and 81 columns

(1460, 81)

In [11]:
Training_dataset.isnull().sum() # to get total null values in a column

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

# **DATA PRE-PROCESSING for the purpose of training the model**

In [12]:
selected_columns = ['LotArea', 'GrLivArea', 'Neighborhood', 'HouseStyle'] # 2 continuos and 2 Categorical
target_column = ['SalePrice'] #Output column

In [13]:
Columns_selected = Training_dataset[selected_columns]
Columns_selected

      LotArea  GrLivArea Neighborhood HouseStyle
0        8450       1710      CollgCr     2Story
1        9600       1262      Veenker     1Story
2       11250       1786      CollgCr     2Story
3        9550       1717      Crawfor     2Story
4       14260       2198      NoRidge     2Story
...       ...        ...          ...        ...
1455     7917       1647      Gilbert     2Story
1456    13175       2073       NWAmes     1Story
1457     9042       2340      Crawfor     2Story
1458     9717       1078        NAmes     1Story
1459     9937       1256      Edwards     1Story

[1460 rows x 4 columns]

In [14]:
Columns_selected.isnull().sum() #checking if there's any null value

LotArea         0
GrLivArea       0
Neighborhood    0
HouseStyle      0
dtype: int64

In [15]:
target_attribute = Training_dataset[target_column]
target_attribute

      SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [16]:
target_attribute.isnull().sum() #checking if there's any null values

SalePrice    0
dtype: int64

In [17]:
continuos_datatype_col = ['LotArea', 'GrLivArea']
discrete_datatype_col = ['Neighborhood', 'HouseStyle']

In [18]:
merged_attributes = pd.concat([Columns_selected,target_attribute], axis=1)
merged_attributes #concatenating selected features together as single dataframe

      LotArea  GrLivArea Neighborhood HouseStyle  SalePrice
0        8450       1710      CollgCr     2Story     208500
1        9600       1262      Veenker     1Story     181500
2       11250       1786      CollgCr     2Story     223500
3        9550       1717      Crawfor     2Story     140000
4       14260       2198      NoRidge     2Story     250000
...       ...        ...          ...        ...        ...
1455     7917       1647      Gilbert     2Story     175000
1456    13175       2073       NWAmes     1Story     210000
1457     9042       2340      Crawfor     2Story     266500
1458     9717       1078        NAmes     1Story     142125
1459     9937       1256      Edwards     1Story     147500

[1460 rows x 5 columns]

In [19]:
Columns_selected['Neighborhood'].nunique() #to get the count of different values from the categorical data type column

25

In [20]:
Columns_selected['HouseStyle'].nunique() #to get the count of different values from the categorical data type column

8

In [21]:
implementing_one_hot_encode_Neighborhood = pd.get_dummies(merged_attributes[discrete_datatype_col])
implementing_one_hot_encode_Neighborhood.head() #performing one hot encoding for the selected discrete(categorical) features

,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,...,Neighborhood_Timber,Neighborhood_Veenker,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

# **Scaling columns that has continuos data types (LotArea, GrLivArea)**

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [23]:
scaler.fit_transform(merged_attributes[continuos_datatype_col])

array([[-0.20714171,  0.37033344],
       [-0.09188637, -0.48251191],
       [ 0.07347998,  0.51501256],
       ...,
       [-0.14781027,  1.56964722],
       [-0.08016039, -0.83278768],
       [-0.05811155, -0.49393395]])

In [24]:
df_continuos_features = merged_attributes[['LotArea','GrLivArea']] 
df_continuos_features

      LotArea  GrLivArea
0        8450       1710
1        9600       1262
2       11250       1786
3        9550       1717
4       14260       2198
...       ...        ...
1455     7917       1647
1456    13175       2073
1457     9042       2340
1458     9717       1078
1459     9937       1256

[1460 rows x 2 columns]

In [25]:
 df_continuos_features[continuos_datatype_col] = scaler.fit_transform(merged_attributes[continuos_datatype_col])
 df_continuos_features

C:\Users\edwin victor\AppData\Local\Temp\ipykernel_6196\3894193502.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_continuos_features[continuos_datatype_col] = scaler.fit_transform(merged_attributes[continuos_datatype_col])

       LotArea  GrLivArea
0    -0.207142   0.370333
1    -0.091886  -0.482512
2     0.073480   0.515013
3    -0.096897   0.383659
4     0.375148   1.299326
...        ...        ...
1455 -0.260560   0.250402
1456  0.266407   1.061367
1457 -0.147810   1.569647
1458 -0.080160  -0.832788
1459 -0.058112  -0.493934

[1460 rows x 2 columns]

In [26]:
concatenating_encoded_scaled_df = pd.concat([df_continuos_features, implementing_one_hot_encode_Neighborhood], axis=1)
concatenating_encoded_scaled_df_1 = pd.concat([concatenating_encoded_scaled_df,target_attribute], axis=1)
concatenating_encoded_scaled_df_1

,LotArea,GrLivArea,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,...,Neighborhood_Veenker,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,SalePrice
0,-0.207142,0.370333,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,208500
1,-0.091886,-0.482512,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,181500
2,0.073480,0.515013,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,223500
3,-0.096897,0.383659,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,140000
4,0.375148,1.299326,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,-0.260560,0.250402,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,175000
1456,0.266407,1.061367,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,210000
1457,-0.147810,1.569647,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,266500
1458,-0.080160,-0.832788,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,142125
1459,-0.058112,-0.493934,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,147500

# **Training the Model using the after the selected features is processed and prepared**

In [27]:
X = concatenating_encoded_scaled_df_1.drop(columns= target_column)  
y = concatenating_encoded_scaled_df_1[target_column]

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression() #training the model with linear regression

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=50)

In [30]:
model.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = model.predict(X_test)

# checking accuracy of our model

In [32]:
from sklearn.metrics import mean_squared_log_error
import numpy as np
Rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred)) #rmse = root mean squared error
print ("Root Mean Squared Error:", Rmsle * 100) #using rmse metric to check how good our model has performed

Root Mean Squared Error: 19.12028656482006